### PR TITLE
use cryptographically secure random function

### LINKED ISSUE #4: Math.random() is not
Shouldn't use built in JS Math.random() since it will repeat itself; too dangerous to use for 'Unique ID' etc.
https://medium.com/@betable/tifu-by-using-math-random-f1c308c4fd9d#.uskhjv9vc

Might be a while before I can even copy/paste & quick test a solution from there, let alone add the 'white noise' & other repeating tests.

tr;dr: "[use urandom](http://sockpuppet.org/blog/2014/02/25/safely-generate-random-numbers/). In browser you can use [crypto.getRandomValues()](https://developer.mozilla.org/en-US/docs/Web/API/RandomSource/getRandomValues)"  I'm not sure if V8's `crypto.getRandomValues()` can be exposed in node; seems to have its own crypto lib.  But node does have [crypto.randomBytes(size[, callback])](https://nodejs.org/api/crypto.html#crypto_crypto_randombytes_size_callback)

### PR DESCRIPTION
**Pull request by michaelrhodes**
Closes #4

### CODE REVIEW

**Comment by michaelrhodes** [comment]
It might also be worth exporting `require('math-random').cryptographic` so that older browsers can easily check which type of random function is being used

**Comment by doowb** [comment]
I think this looks great. I think adding the `.cryptographic` property is a good idea to give browser app implementors the choice on if they want to support older browsers.

**Comment by michaelrhodes** [comment]
Agreed. I’ll update the pull request? And if so, what’s your preferred property name? Is `cryptographic` fine, or should I go for something more descriptive like `isCryptographicallySecure` or `isSecure`?

**Comment by doowb** [comment]
I think `.isCrypto` is good.

Also, add some documentation to [.verb.md](https://github.com/jonschlinkert/randomatic/blob/master/.verb.md) that explains what it means. I think it's fine to say something like, "`isCrypto` will be `true` when a cryptographic library is being used, otherwise, `Math.random` is being used."

**Comment by jonschlinkert** [comment]
> I think .isCrypto is good.

Agreed, I think `isCrypto` makes sense since it's a boolean confirming that the built-in `crypto` lib was used. 

Nice work, thanks!

**Comment by michaelrhodes** [comment]
Okie dokie gang, I believe this is good to go now :)

**Comment by jonschlinkert** [comment]
thanks! published and released as 3.0.0!

**Comment by tomByrer** [comment]
Cheers @michaelrhodes & @jonschlinkert

**Pull request merged**
